// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Info");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 30,
                            Gender = "male",
                            Info = "Lovely orange kitty, very nice and lovely.",
                            Name = "Nepolian",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            Gender = "male",
                            Info = "Lovely doggo, very nice and snuggly black lab.",
                            Name = "Charlitan",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 1,
                            Gender = "male",
                            Info = "Black cat, loves to snuggle.",
                            Name = "Maxamillion",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Gender = "female",
                            Info = "Kind and loving calico, occasionally fiesty.",
                            Name = "Hillary",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 300,
                            Gender = "female",
                            Info = "Purple kitty, ancient and full of wisdom. Great pal.",
                            Name = "Heceta",
                            Species = "cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
